export enum Religion {
  CHRISTIANITY = "christianity",
  ISLAM = "islam",
  BUDDHISM = "buddhism",
  JUDAISM = "judaism",
  SIKHISM = "sikhism",
  BAHAI = "bahai",
  JAINISM = "jainism",
  SHINTO = "shinto",
  TAOISM = "taoism",
  ZOROASTRIANISM = "zoroastrianism",
  CONFUCIANISM = "confucianism",
  ANIMISM = "animism",
  PAGANISM = "paganism",
  AGNOSTICISM = "agnosticism",
  ATHEISM = "atheism",
  HINDUISM = "hinduism",
}
