const BASE_URL = "https://quranic-miracles.vercel.app/";

export const scienceItems = [
  {
    title: "Magnetosphere",
    description: "An entry about Magnetosphere in the field of Astronomy.",
    url: `${BASE_URL}astronomy/magnetosphere`,
    fieldOfScience: "ASTRONOMY",
    tags: ["Magnetosphere", "Astronomy", "Science"],
  },
  {
    title: "Moonlight",
    description: "An entry about Moonlight in the field of Astronomy.",
    url: `${BASE_URL}astronomy/moonlight`,
    fieldOfScience: "ASTRONOMY",
    tags: ["Moonlight", "Astronomy", "Science"],
  },
  {
    title: "Planetary Orbits",
    description: "An entry about Planetary Orbits in the field of Astronomy.",
    url: `${BASE_URL}astronomy/planetary-orbits`,
    fieldOfScience: "ASTRONOMY",
    tags: ["Planetary", "Astronomy", "Science"],
  },
  {
    title: "Red Giant",
    description: "An entry about Red Giant in the field of Astronomy.",
    url: `${BASE_URL}astronomy/red-giant`,
    fieldOfScience: "ASTRONOMY",
    tags: ["Red", "Astronomy", "Science"],
  },
  {
    title: "Sirius",
    description: "An entry about Sirius in the field of Astronomy.",
    url: `${BASE_URL}astronomy/sirius`,
    fieldOfScience: "ASTRONOMY",
    tags: ["Sirius", "Astronomy", "Science"],
  },
  {
    title: "Starlight",
    description: "An entry about Starlight in the field of Astronomy.",
    url: `${BASE_URL}astronomy/starlight`,
    fieldOfScience: "ASTRONOMY",
    tags: ["Starlight", "Astronomy", "Science"],
  },
  {
    title: "Tidal Locking",
    description: "An entry about Tidal Locking in the field of Astronomy.",
    url: `${BASE_URL}astronomy/tidal-locking`,
    fieldOfScience: "ASTRONOMY",
    tags: ["Tidal", "Astronomy", "Science"],
  },
  {
    title: "Breastfeeding",
    description: "An entry about Breastfeeding in the field of Biology.",
    url: `${BASE_URL}biology/breastfeeding`,
    fieldOfScience: "BIOLOGY",
    tags: ["Breastfeeding", "Biology", "Science"],
  },
  {
    title: "Fasting",
    description: "An entry about Fasting in the field of Biology.",
    url: `${BASE_URL}biology/fasting`,
    fieldOfScience: "BIOLOGY",
    tags: ["Fasting", "Biology", "Science"],
  },
  {
    title: "Gardens",
    description: "An entry about Gardens in the field of Biology.",
    url: `${BASE_URL}biology/gardens`,
    fieldOfScience: "BIOLOGY",
    tags: ["Gardens", "Biology", "Science"],
  },
  {
    title: "Honey",
    description: "An entry about Honey in the field of Biology.",
    url: `${BASE_URL}biology/honey`,
    fieldOfScience: "BIOLOGY",
    tags: ["Honey", "Biology", "Science"],
  },
  {
    title: "Hypoxia",
    description: "An entry about Hypoxia in the field of Biology.",
    url: `${BASE_URL}biology/hypoxia`,
    fieldOfScience: "BIOLOGY",
    tags: ["Hypoxia", "Biology", "Science"],
  },
  {
    title: "Keraunoparalysis",
    description: "An entry about Keraunoparalysis in the field of Biology.",
    url: `${BASE_URL}biology/keraunoparalysis`,
    fieldOfScience: "BIOLOGY",
    tags: ["Keraunoparalysis", "Biology", "Science"],
  },
  {
    title: "Plant Stress",
    description: "An entry about Plant Stress in the field of Biology.",
    url: `${BASE_URL}biology/plant-stress`,
    fieldOfScience: "BIOLOGY",
    tags: ["Plant", "Biology", "Science"],
  },
  {
    title: "Pollination",
    description: "An entry about Pollination in the field of Biology.",
    url: `${BASE_URL}biology/pollination`,
    fieldOfScience: "BIOLOGY",
    tags: ["Pollination", "Biology", "Science"],
  },
  {
    title: "White Hair",
    description: "An entry about White Hair in the field of Biology.",
    url: `${BASE_URL}biology/white-hair`,
    fieldOfScience: "BIOLOGY",
    tags: ["White", "Biology", "Science"],
  },
  {
    title: "Halocline",
    description: "An entry about Halocline in the field of Chemistry.",
    url: `${BASE_URL}chemistry/halocline`,
    fieldOfScience: "CHEMISTRY",
    tags: ["Halocline", "Chemistry", "Science"],
  },
  {
    title: "Iron",
    description: "An entry about Iron in the field of Chemistry.",
    url: `${BASE_URL}chemistry/iron`,
    fieldOfScience: "CHEMISTRY",
    tags: ["Iron", "Chemistry", "Science"],
  },
  {
    title: "Pyritized Fossils",
    description: "An entry about Pyritized Fossils in the field of Chemistry.",
    url: `${BASE_URL}chemistry/pyritized-fossils`,
    fieldOfScience: "CHEMISTRY",
    tags: ["Pyritized", "Chemistry", "Science"],
  },
  {
    title: "Superionic Water",
    description: "An entry about Superionic Water in the field of Chemistry.",
    url: `${BASE_URL}chemistry/superionic-water`,
    fieldOfScience: "CHEMISTRY",
    tags: ["Superionic", "Chemistry", "Science"],
  },
  {
    title: "Age Of Universe",
    description: "An entry about Age Of Universe in the field of Cosmology.",
    url: `${BASE_URL}cosmology/age-of-universe`,
    fieldOfScience: "COSMOLOGY",
    tags: ["Age", "Cosmology", "Science"],
  },
  {
    title: "Big Bang",
    description: "An entry about Big Bang in the field of Cosmology.",
    url: `${BASE_URL}cosmology/big-bang`,
    fieldOfScience: "COSMOLOGY",
    tags: ["Big", "Cosmology", "Science"],
  },
  {
    title: "Big Crunch",
    description: "An entry about Big Crunch in the field of Cosmology.",
    url: `${BASE_URL}cosmology/big-crunch`,
    fieldOfScience: "COSMOLOGY",
    tags: ["Big", "Cosmology", "Science"],
  },
  {
    title: "Dark Energy",
    description: "An entry about Dark Energy in the field of Cosmology.",
    url: `${BASE_URL}cosmology/dark-energy`,
    fieldOfScience: "COSMOLOGY",
    tags: ["Dark", "Cosmology", "Science"],
  },
  {
    title: "Expanding Universe",
    description: "An entry about Expanding Universe in the field of Cosmology.",
    url: `${BASE_URL}cosmology/expanding-universe`,
    fieldOfScience: "COSMOLOGY",
    tags: ["Expanding", "Cosmology", "Science"],
  },
  {
    title: "Gravitation Waves",
    description: "An entry about Gravitation Waves in the field of Cosmology.",
    url: `${BASE_URL}cosmology/gravitation-waves`,
    fieldOfScience: "COSMOLOGY",
    tags: ["Gravitation", "Cosmology", "Science"],
  },
  {
    title: "Gravity",
    description: "An entry about Gravity in the field of Cosmology.",
    url: `${BASE_URL}cosmology/gravity`,
    fieldOfScience: "COSMOLOGY",
    tags: ["Gravity", "Cosmology", "Science"],
  },
  {
    title: "Primordial Smoke",
    description: "An entry about Primordial Smoke in the field of Cosmology.",
    url: `${BASE_URL}cosmology/primordial-smoke`,
    fieldOfScience: "COSMOLOGY",
    tags: ["Primordial", "Cosmology", "Science"],
  },
  {
    title: "Red Shifting",
    description: "An entry about Red Shifting in the field of Cosmology.",
    url: `${BASE_URL}cosmology/red-shifting`,
    fieldOfScience: "COSMOLOGY",
    tags: ["Red", "Cosmology", "Science"],
  },
  {
    title: "Seven Heavens",
    description: "An entry about Seven Heavens in the field of Cosmology.",
    url: `${BASE_URL}cosmology/seven-heavens`,
    fieldOfScience: "COSMOLOGY",
    tags: ["Seven", "Cosmology", "Science"],
  },
  {
    title: "Shape of Universe",
    description: "An entry about Shape of Universe in the field of Cosmology.",
    url: `${BASE_URL}cosmology/shape-of-universe`,
    fieldOfScience: "COSMOLOGY",
    tags: ["Shape", "Cosmology", "Science"],
  },
  {
    title: "Bones",
    description: "An entry about Bones in the field of Embryology.",
    url: `${BASE_URL}embryology/bones`,
    fieldOfScience: "EMBRYOLOGY",
    tags: ["Bones", "Embryology", "Science"],
  },
  {
    title: "Fetal Development",
    description: "An entry about Fetal Development in the field of Embryology.",
    url: `${BASE_URL}embryology/fetal-development`,
    fieldOfScience: "EMBRYOLOGY",
    tags: ["Fetal", "Embryology", "Science"],
  },
  {
    title: "Gender",
    description: "An entry about Gender in the field of Embryology.",
    url: `${BASE_URL}embryology/gender`,
    fieldOfScience: "EMBRYOLOGY",
    tags: ["Gender", "Embryology", "Science"],
  },
  {
    title: "Human Embryo",
    description: "An entry about Human Embryo in the field of Embryology.",
    url: `${BASE_URL}embryology/human-embryo`,
    fieldOfScience: "EMBRYOLOGY",
    tags: ["Human", "Embryology", "Science"],
  },
  {
    title: "Human Senses",
    description: "An entry about Human Senses in the field of Embryology.",
    url: `${BASE_URL}embryology/human-senses`,
    fieldOfScience: "EMBRYOLOGY",
    tags: ["Human", "Embryology", "Science"],
  },
  {
    title: "Asthenosphere",
    description: "An entry about Asthenosphere in the field of Geology.",
    url: `${BASE_URL}geology/asthenosphere`,
    fieldOfScience: "GEOLOGY",
    tags: ["Asthenosphere", "Geology", "Science"],
  },
  {
    title: "Coal",
    description: "An entry about Coal in the field of Geology.",
    url: `${BASE_URL}geology/coal`,
    fieldOfScience: "GEOLOGY",
    tags: ["Coal", "Geology", "Science"],
  },
  {
    title: "Earth",
    description: "An entry about Earth in the field of Geology.",
    url: `${BASE_URL}geology/earth`,
    fieldOfScience: "GEOLOGY",
    tags: ["Earth", "Geology", "Science"],
  },
  {
    title: "Earthquake",
    description: "An entry about Earthquake in the field of Geology.",
    url: `${BASE_URL}geology/earthquake`,
    fieldOfScience: "GEOLOGY",
    tags: ["Earthquake", "Geology", "Science"],
  },
  {
    title: "Fault Lines",
    description: "An entry about Fault Lines in the field of Geology.",
    url: `${BASE_URL}geology/fault-lines`,
    fieldOfScience: "GEOLOGY",
    tags: ["Fault", "Geology", "Science"],
  },
  {
    title: "Internal Mountains",
    description: "An entry about Internal Mountains in the field of Geology.",
    url: `${BASE_URL}geology/internal-mountains`,
    fieldOfScience: "GEOLOGY",
    tags: ["Internal", "Geology", "Science"],
  },
  {
    title: "Internal Waves",
    description: "An entry about Internal Waves in the field of Geology.",
    url: `${BASE_URL}geology/internal-waves`,
    fieldOfScience: "GEOLOGY",
    tags: ["Internal", "Geology", "Science"],
  },
  {
    title: "Landslides",
    description: "An entry about Landslides in the field of Geology.",
    url: `${BASE_URL}geology/landslides`,
    fieldOfScience: "GEOLOGY",
    tags: ["Landslides", "Geology", "Science"],
  },
  {
    title: "Mountain",
    description: "An entry about Mountain in the field of Geology.",
    url: `${BASE_URL}geology/mountain`,
    fieldOfScience: "GEOLOGY",
    tags: ["Mountain", "Geology", "Science"],
  },
  {
    title: "Photic Zone",
    description: "An entry about Photic Zone in the field of Geology.",
    url: `${BASE_URL}geology/photic-zone`,
    fieldOfScience: "GEOLOGY",
    tags: ["Photic", "Geology", "Science"],
  },
  {
    title: "Porous Rocks",
    description: "An entry about Porous Rocks in the field of Geology.",
    url: `${BASE_URL}geology/porous-rocks`,
    fieldOfScience: "GEOLOGY",
    tags: ["Porous", "Geology", "Science"],
  },
  {
    title: "Pumice",
    description: "An entry about Pumice in the field of Geology.",
    url: `${BASE_URL}geology/pumice`,
    fieldOfScience: "GEOLOGY",
    tags: ["Pumice", "Geology", "Science"],
  },
  {
    title: "Sinkhole",
    description: "An entry about Sinkhole in the field of Geology.",
    url: `${BASE_URL}geology/sinkhole`,
    fieldOfScience: "GEOLOGY",
    tags: ["Sinkhole", "Geology", "Science"],
  },
  {
    title: "Soil Expansion",
    description: "An entry about Soil Expansion in the field of Geology.",
    url: `${BASE_URL}geology/soil-expansion`,
    fieldOfScience: "GEOLOGY",
    tags: ["Soil", "Geology", "Science"],
  },
  {
    title: "Steam Explosions",
    description: "An entry about Steam Explosions in the field of Geology.",
    url: `${BASE_URL}geology/steam-explosions`,
    fieldOfScience: "GEOLOGY",
    tags: ["Steam", "Geology", "Science"],
  },
  {
    title: "Subduction",
    description: "An entry about Subduction in the field of Geology.",
    url: `${BASE_URL}geology/subduction`,
    fieldOfScience: "GEOLOGY",
    tags: ["Subduction", "Geology", "Science"],
  },
  {
    title: "Tectonics",
    description: "An entry about Tectonics in the field of Geology.",
    url: `${BASE_URL}geology/tectonics`,
    fieldOfScience: "GEOLOGY",
    tags: ["Tectonics", "Geology", "Science"],
  },
  {
    title: "Volcano",
    description: "An entry about Volcano in the field of Geology.",
    url: `${BASE_URL}geology/volcano`,
    fieldOfScience: "GEOLOGY",
    tags: ["Volcano", "Geology", "Science"],
  },
  {
    title: "Weathering & Erosions",
    description:
      "An entry about Weathering & Erosions in the field of Geology.",
    url: `${BASE_URL}geology/weathering--erosions`,
    fieldOfScience: "GEOLOGY",
    tags: ["Weathering", "Geology", "Science"],
  },
  {
    title: "Crucifixtion",
    description: "An entry about Crucifixtion in the field of History.",
    url: `${BASE_URL}history/crucifixtion`,
    fieldOfScience: "HISTORY",
    tags: ["Crucifixtion", "History", "Science"],
  },
  {
    title: "Deities",
    description: "An entry about Deities in the field of History.",
    url: `${BASE_URL}history/deities`,
    fieldOfScience: "HISTORY",
    tags: ["Deities", "History", "Science"],
  },
  {
    title: "Dried River",
    description: "An entry about Dried River in the field of History.",
    url: `${BASE_URL}history/dried-river`,
    fieldOfScience: "HISTORY",
    tags: ["Dried", "History", "Science"],
  },
  {
    title: "Flight",
    description: "An entry about Flight in the field of History.",
    url: `${BASE_URL}history/flight`,
    fieldOfScience: "HISTORY",
    tags: ["Flight", "History", "Science"],
  },
  {
    title: "Haman",
    description: "An entry about Haman in the field of History.",
    url: `${BASE_URL}history/haman`,
    fieldOfScience: "HISTORY",
    tags: ["Haman", "History", "Science"],
  },
  {
    title: "Karnak Temple",
    description: "An entry about Karnak Temple in the field of History.",
    url: `${BASE_URL}history/karnak-temple`,
    fieldOfScience: "HISTORY",
    tags: ["Karnak", "History", "Science"],
  },
  {
    title: "Moses",
    description: "An entry about Moses in the field of History.",
    url: `${BASE_URL}history/moses`,
    fieldOfScience: "HISTORY",
    tags: ["Moses", "History", "Science"],
  },
  {
    title: "Mourning of Pharoah",
    description: "An entry about Mourning of Pharoah in the field of History.",
    url: `${BASE_URL}history/mourning-of-pharoah`,
    fieldOfScience: "HISTORY",
    tags: ["Mourning", "History", "Science"],
  },
  {
    title: "Noah",
    description: "An entry about Noah in the field of History.",
    url: `${BASE_URL}history/noah`,
    fieldOfScience: "HISTORY",
    tags: ["Noah", "History", "Science"],
  },
  {
    title: "Petra",
    description: "An entry about Petra in the field of History.",
    url: `${BASE_URL}history/petra`,
    fieldOfScience: "HISTORY",
    tags: ["Petra", "History", "Science"],
  },
  {
    title: "Pharoah",
    description: "An entry about Pharoah in the field of History.",
    url: `${BASE_URL}history/pharoah`,
    fieldOfScience: "HISTORY",
    tags: ["Pharoah", "History", "Science"],
  },
  {
    title: "Pharoah Mummy",
    description: "An entry about Pharoah Mummy in the field of History.",
    url: `${BASE_URL}history/pharoah-mummy`,
    fieldOfScience: "HISTORY",
    tags: ["Pharoah", "History", "Science"],
  },
  {
    title: "Ubar",
    description: "An entry about Ubar in the field of History.",
    url: `${BASE_URL}history/ubar`,
    fieldOfScience: "HISTORY",
    tags: ["Ubar", "History", "Science"],
  },
  {
    title: "Abjad Numerals",
    description: "An entry about Abjad Numerals in the field of Math.",
    url: `${BASE_URL}math/abjad-numerals`,
    fieldOfScience: "MATH",
    tags: ["Abjad", "Math", "Science"],
  },
  {
    title: "Base 19",
    description: "An entry about Base 19 in the field of Math.",
    url: `${BASE_URL}math/base-19`,
    fieldOfScience: "MATH",
    tags: ["Base", "Math", "Science"],
  },
  {
    title: "Encoding",
    description: "An entry about Encoding in the field of Math.",
    url: `${BASE_URL}math/encoding`,
    fieldOfScience: "MATH",
    tags: ["Encoding", "Math", "Science"],
  },
  {
    title: "Hypersonic",
    description: "An entry about Hypersonic in the field of Math.",
    url: `${BASE_URL}math/hypersonic`,
    fieldOfScience: "MATH",
    tags: ["Hypersonic", "Math", "Science"],
  },
  {
    title: "Kilometer",
    description: "An entry about Kilometer in the field of Math.",
    url: `${BASE_URL}math/kilometer`,
    fieldOfScience: "MATH",
    tags: ["Kilometer", "Math", "Science"],
  },
  {
    title: "Light Year",
    description: "An entry about Light Year in the field of Math.",
    url: `${BASE_URL}math/light-year`,
    fieldOfScience: "MATH",
    tags: ["Light", "Math", "Science"],
  },
  {
    title: "Meter",
    description: "An entry about Meter in the field of Math.",
    url: `${BASE_URL}math/meter`,
    fieldOfScience: "MATH",
    tags: ["Meter", "Math", "Science"],
  },
  {
    title: "Miles",
    description: "An entry about Miles in the field of Math.",
    url: `${BASE_URL}math/miles`,
    fieldOfScience: "MATH",
    tags: ["Miles", "Math", "Science"],
  },
  {
    title: "Pi",
    description: "An entry about Pi in the field of Math.",
    url: `${BASE_URL}math/pi`,
    fieldOfScience: "MATH",
    tags: ["Pi", "Math", "Science"],
  },
  {
    title: "Prime Numbers",
    description: "An entry about Prime Numbers in the field of Math.",
    url: `${BASE_URL}math/prime-numbers`,
    fieldOfScience: "MATH",
    tags: ["Prime", "Math", "Science"],
  },
  {
    title: "Pulsar Navigation",
    description: "An entry about Pulsar Navigation in the field of Math.",
    url: `${BASE_URL}math/pulsar-navigation`,
    fieldOfScience: "MATH",
    tags: ["Pulsar", "Math", "Science"],
  },
  {
    title: "Atmosphere",
    description: "An entry about Atmosphere in the field of Meteorology.",
    url: `${BASE_URL}meteorology/atmosphere`,
    fieldOfScience: "METEOROLOGY",
    tags: ["Atmosphere", "Meteorology", "Science"],
  },
  {
    title: "Atmospheric Pressure",
    description:
      "An entry about Atmospheric Pressure in the field of Meteorology.",
    url: `${BASE_URL}meteorology/atmospheric-pressure`,
    fieldOfScience: "METEOROLOGY",
    tags: ["Atmospheric", "Meteorology", "Science"],
  },
  {
    title: "Desertification",
    description: "An entry about Desertification in the field of Meteorology.",
    url: `${BASE_URL}meteorology/desertification`,
    fieldOfScience: "METEOROLOGY",
    tags: ["Desertification", "Meteorology", "Science"],
  },
  {
    title: "Water",
    description: "An entry about Water in the field of Meteorology.",
    url: `${BASE_URL}meteorology/water`,
    fieldOfScience: "METEOROLOGY",
    tags: ["Water", "Meteorology", "Science"],
  },
  {
    title: "Water Cycle",
    description: "An entry about Water Cycle in the field of Meteorology.",
    url: `${BASE_URL}meteorology/water-cycle`,
    fieldOfScience: "METEOROLOGY",
    tags: ["Water", "Meteorology", "Science"],
  },
  {
    title: "Weight of Clouds",
    description: "An entry about Weight of Clouds in the field of Meteorology.",
    url: `${BASE_URL}meteorology/weight-of-clouds`,
    fieldOfScience: "METEOROLOGY",
    tags: ["Weight", "Meteorology", "Science"],
  },
  {
    title: "Atom",
    description: "An entry about Atom in the field of Physics.",
    url: `${BASE_URL}physics/atom`,
    fieldOfScience: "PHYSICS",
    tags: ["Atom", "Physics", "Science"],
  },
  {
    title: "Pairs",
    description: "An entry about Pairs in the field of Physics.",
    url: `${BASE_URL}physics/pairs`,
    fieldOfScience: "PHYSICS",
    tags: ["Pairs", "Physics", "Science"],
  },
  {
    title: "Pulsar",
    description: "An entry about Pulsar in the field of Physics.",
    url: `${BASE_URL}physics/pulsar`,
    fieldOfScience: "PHYSICS",
    tags: ["Pulsar", "Physics", "Science"],
  },
  {
    title: "Solar Energy",
    description: "An entry about Solar Energy in the field of Physics.",
    url: `${BASE_URL}physics/solar-energy`,
    fieldOfScience: "PHYSICS",
    tags: ["Solar", "Physics", "Science"],
  },
  {
    title: "Sonic Weapons",
    description: "An entry about Sonic Weapons in the field of Physics.",
    url: `${BASE_URL}physics/sonic-weapons`,
    fieldOfScience: "PHYSICS",
    tags: ["Sonic", "Physics", "Science"],
  },
  {
    title: "String Theory",
    description: "An entry about String Theory in the field of Physics.",
    url: `${BASE_URL}physics/string-theory`,
    fieldOfScience: "PHYSICS",
    tags: ["String", "Physics", "Science"],
  },
  {
    title: "Work",
    description: "An entry about Work in the field of Physics.",
    url: `${BASE_URL}physics/work`,
    fieldOfScience: "PHYSICS",
    tags: ["Work", "Physics", "Science"],
  },
  {
    title: "Wormhole",
    description: "An entry about Wormhole in the field of Physics.",
    url: `${BASE_URL}physics/wormhole`,
    fieldOfScience: "PHYSICS",
    tags: ["Wormhole", "Physics", "Science"],
  },
  {
    title: "Brain Function",
    description: "An entry about Brain Function in the field of Physiology.",
    url: `${BASE_URL}physiology/brain-function`,
    fieldOfScience: "PHYSIOLOGY",
    tags: ["Brain", "Physiology", "Science"],
  },
  {
    title: "Brain Stem",
    description: "An entry about Brain Stem in the field of Physiology.",
    url: `${BASE_URL}physiology/brain-stem`,
    fieldOfScience: "PHYSIOLOGY",
    tags: ["Brain", "Physiology", "Science"],
  },
  {
    title: "Ear Drum",
    description: "An entry about Ear Drum in the field of Physiology.",
    url: `${BASE_URL}physiology/ear-drum`,
    fieldOfScience: "PHYSIOLOGY",
    tags: ["Ear", "Physiology", "Science"],
  },
  {
    title: "Finger Prints",
    description: "An entry about Finger Prints in the field of Physiology.",
    url: `${BASE_URL}physiology/finger-prints`,
    fieldOfScience: "PHYSIOLOGY",
    tags: ["Finger", "Physiology", "Science"],
  },
  {
    title: "Flash Blindness",
    description: "An entry about Flash Blindness in the field of Physiology.",
    url: `${BASE_URL}physiology/flash-blindness`,
    fieldOfScience: "PHYSIOLOGY",
    tags: ["Flash", "Physiology", "Science"],
  },
  {
    title: "Milk",
    description: "An entry about Milk in the field of Physiology.",
    url: `${BASE_URL}physiology/milk`,
    fieldOfScience: "PHYSIOLOGY",
    tags: ["Milk", "Physiology", "Science"],
  },
  {
    title: "Neurons",
    description: "An entry about Neurons in the field of Physiology.",
    url: `${BASE_URL}physiology/neurons`,
    fieldOfScience: "PHYSIOLOGY",
    tags: ["Neurons", "Physiology", "Science"],
  },
  {
    title: "Skin Nerves",
    description: "An entry about Skin Nerves in the field of Physiology.",
    url: `${BASE_URL}physiology/skin-nerves`,
    fieldOfScience: "PHYSIOLOGY",
    tags: ["Skin", "Physiology", "Science"],
  },
  {
    title: "Animal Language",
    description: "An entry about Animal Language in the field of Zoology.",
    url: `${BASE_URL}zoology/animal-language`,
    fieldOfScience: "ZOOLOGY",
    tags: ["Animal", "Zoology", "Science"],
  },
  {
    title: "Ants",
    description: "An entry about Ants in the field of Zoology.",
    url: `${BASE_URL}zoology/ants`,
    fieldOfScience: "ZOOLOGY",
    tags: ["Ants", "Zoology", "Science"],
  },
  {
    title: "Camels",
    description: "An entry about Camels in the field of Zoology.",
    url: `${BASE_URL}zoology/camels`,
    fieldOfScience: "ZOOLOGY",
    tags: ["Camels", "Zoology", "Science"],
  },
  {
    title: "Colonies",
    description: "An entry about Colonies in the field of Zoology.",
    url: `${BASE_URL}zoology/colonies`,
    fieldOfScience: "ZOOLOGY",
    tags: ["Colonies", "Zoology", "Science"],
  },
  {
    title: "Crow",
    description: "An entry about Crow in the field of Zoology.",
    url: `${BASE_URL}zoology/crow`,
    fieldOfScience: "ZOOLOGY",
    tags: ["Crow", "Zoology", "Science"],
  },
  {
    title: "Exoskeleton",
    description: "An entry about Exoskeleton in the field of Zoology.",
    url: `${BASE_URL}zoology/exoskeleton`,
    fieldOfScience: "ZOOLOGY",
    tags: ["Exoskeleton", "Zoology", "Science"],
  },
  {
    title: "Honey Bees",
    description: "An entry about Honey Bees in the field of Zoology.",
    url: `${BASE_URL}zoology/honey-bees`,
    fieldOfScience: "ZOOLOGY",
    tags: ["Honey", "Zoology", "Science"],
  },
  {
    title: "Housefly",
    description: "An entry about Housefly in the field of Zoology.",
    url: `${BASE_URL}zoology/housefly`,
    fieldOfScience: "ZOOLOGY",
    tags: ["Housefly", "Zoology", "Science"],
  },
  {
    title: "Mosquito",
    description: "An entry about Mosquito in the field of Zoology.",
    url: `${BASE_URL}zoology/mosquito`,
    fieldOfScience: "ZOOLOGY",
    tags: ["Mosquito", "Zoology", "Science"],
  },
  {
    title: "Raptor",
    description: "An entry about Raptor in the field of Zoology.",
    url: `${BASE_URL}zoology/raptor`,
    fieldOfScience: "ZOOLOGY",
    tags: ["Raptor", "Zoology", "Science"],
  },
  {
    title: "Spider Web",
    description: "An entry about Spider Web in the field of Zoology.",
    url: `${BASE_URL}zoology/spider-web`,
    fieldOfScience: "ZOOLOGY",
    tags: ["Spider", "Zoology", "Science"],
  },
];
